# Generated by Django 3.0.3 on 2020-07-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='apresentacao',
        ),
        migrations.AddField(
            model_name='homepage',
            name='citacao',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
