# Generated by Django 3.0.3 on 2020-07-18 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0005_homepage_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueNomeHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
            managers=[
                ('teams', django.db.models.manager.Manager()),
            ],
        ),
    ]
