# Generated by Django 3.0.3 on 2020-07-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0006_quenomehome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueNomeHome',
        ),
    ]
