# Generated by Django 3.0.3 on 2020-07-23 17:43

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagequenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='texto',
        ),
        migrations.AddField(
            model_name='homepage',
            name='interesses',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='apresentacao',
            field=models.TextField(blank=True),
        ),
    ]
