# Generated by Django 3.0.3 on 2020-07-23 19:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200723_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='formacoes',
            field=wagtail.core.fields.StreamField([('formal_cousers', wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(help_text='Intitutição', required=True)), ('courses', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(help_text='Curso', icon='plus', required=True), required=True)), ('note', wagtail.core.blocks.CharBlock(help_text='Descreva o estado ou nota final', required=True)), ('begining_date', wagtail.core.blocks.DateBlock(help_text='Data de Incio', required=True)), ('finishing_date', wagtail.core.blocks.DateBlock(help_text='Data de Término', required=False))])), ('free_cousers', wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(help_text='Intitutição', required=True)), ('courses', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(help_text='Curso', icon='plus', required=True)))]))], blank=True, null=True),
        ),
    ]
