# Generated by Django 3.0.3 on 2020-07-23 21:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200723_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='experiencias',
            field=wagtail.core.fields.StreamField([('jobs', wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(help_text='Intitutição', required=True)), ('job', wagtail.core.blocks.CharBlock(help_text='Título', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Descreva o trabalho', required=True)), ('begining_date', wagtail.core.blocks.DateBlock(help_text='Data de Incio', required=True)), ('finishing_date', wagtail.core.blocks.DateBlock(help_text='Data de Término', required=False))]))], blank=True, null=True),
        ),
    ]
