# Generated by Django 3.0.3 on 2020-07-24 00:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='formacoes',
            field=wagtail.core.fields.StreamField([('formal_courses', wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(help_text='Intitutição', required=True)), ('courses', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(help_text='Curso', icon='plus', required=True), required=True)), ('note', wagtail.core.blocks.CharBlock(help_text='Descreva o estado ou nota final', required=True)), ('begining_date', wagtail.core.blocks.DateBlock(help_text='Data de Incio', required=True)), ('finishing_date', wagtail.core.blocks.DateBlock(help_text='Data de Término', required=False))])), ('free_courses', wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(help_text='Intitutição', required=True)), ('courses', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(help_text='Curso', icon='plus', required=True)))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='projetos',
            field=wagtail.core.fields.StreamField([('projects', wagtail.core.blocks.StructBlock([('state', wagtail.core.blocks.ChoiceBlock(choices=[('developing', 'Em desenvolvimento'), ('done', 'Pronto'), ('deployed', 'Deployed'), ('terminated', 'Fora do Ar')], help_text='Estado do desenvolvimento')), ('descrition', wagtail.core.blocks.CharBlock(help_text='Descrição do projeto', required=True)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Nome do Destino', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='URL do Destino', required=False))], icon='plus')))]))], blank=True, null=True),
        ),
    ]
