# Generated by Django 3.0.3 on 2020-07-24 02:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contactbuttons_techicons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techicon',
            name='tech_icon',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Diferentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=60, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferentials', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
