# Generated by Django 3.0.3 on 2020-07-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200723_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='local',
            field=models.CharField(default='cidade, UF País', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='telefone',
            field=models.CharField(default='2222-3412', max_length=250),
            preserve_default=False,
        ),
    ]
