<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-07-18 17:16
=======
# Generated by Django 3.0.7 on 2020-07-14 21:25
>>>>>>> 74158fa133f790eef2dbaacc7130963fa5c60e20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_url', models.URLField()),
                ('team_logo', models.URLField()),
            ],
            options={
                'ordering': ['team_id'],
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('photo', models.URLField()),
<<<<<<< HEAD
                ('birthday', models.DateField(blank=True, null=True)),
=======
                ('birthday', models.DateField()),
>>>>>>> 74158fa133f790eef2dbaacc7130963fa5c60e20
                ('url', models.URLField()),
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_score', models.IntegerField()),
                ('teams', models.ManyToManyField(to='que_nome.Teams')),
            ],
            options={
                'ordering': ['player_id'],
            },
        ),
    ]
