# Generated by Django 3.0.7 on 2020-07-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que_nome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
