# Generated by Django 3.0.7 on 2020-07-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que_nome', '0002_auto_20200714_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
