# Generated by Django 3.0.3 on 2020-07-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que_nome', '0004_playerspage_teamspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='full_name',
            field=models.CharField(default='full_name', max_length=80),
            preserve_default=False,
        ),
    ]
